export const Racers = [
  {
    id: 1,
    firstname: "ROSS",
    lastname: "CHASTAIN",
    picture: "/images/Racers/Racer1.png",
    birthDay: "1992-12-04",
    team: "Trackhouse Racing Team",
    flag: "/images/CarRacingPage/flag1.png",
  },
  {
    id: 2,
    firstname: "AUSTIN",
    lastname: "CINDRIC",
    picture: "/images/Racers/Racer2.png",
    birthDay: "1992-12-04",
    team: "Stewart-Haas Racing",
    flag: "/images/CarRacingPage/flag1.png",
  },
  {
    id: 3,
    firstname: "AUSTIN",
    lastname: "DILLON",
    picture: "/images/Racers/Racer3.png",
    birthDay: "1992-12-04",
    team: "Richard Childress Racing",
    flag: "/images/CarRacingPage/flag1.png",
  },
  {
    id: 4,
    firstname: "KEVIN",
    lastname: "HARVICK",
    picture: "/images/Racers/Racer4.png",
    birthDay: "1992-12-04",
    team: "Stewart-Haas Racing",
    flag: "/images/CarRacingPage/flag1.png",
  },
  {
    id: 5,
    firstname: "KYLE",
    lastname: "LARSON",
    picture: "/images/Racers/Racer5.png",
    birthDay: "1992-12-04",
    team: "Hendrick Motorsports",
    flag: "/images/CarRacingPage/flag1.png",
  },
  {
    id: 6,
    firstname: "COREY",
    lastname: "LAJOIE",
    picture: "/images/Racers/Racer6.png",
    birthDay: "1992-12-04",
    team: "Spire Motorsports",
    flag: "/images/CarRacingPage/flag1.png",
  },
  {
    id: 7,
    firstname: "CHASE",
    lastname: "ELLIOTT",
    picture: "/images/Racers/Racer7.png",
    birthDay: "1992-12-04",
    team: "Hendrick Motorsports",
    flag: "/images/CarRacingPage/flag1.png",
  },
  {
    id: 8,
    firstname: "WILLIAM",
    lastname: "BYRON",
    picture: "/images/Racers/Racer8.png",
    birthDay: "1992-12-04",
    team: "Hendrick Motorsports",
    flag: "/images/CarRacingPage/flag1.png",
  },
  {
    id: 9,
    firstname: "DENNY",
    lastname: "HAMLIN",
    picture: "/images/Racers/Racer9.png",
    birthDay: "1992-12-04",
    team: "Joe Gibbs Racing",
    flag: "/images/CarRacingPage/flag1.png",
  },
  {
    id: 10,
    firstname: "CHRISTOPHER",
    lastname: "BELL",
    picture: "/images/Racers/Racer10.png",
    birthDay: "1992-12-04",
    team: "Joe Gibbs Racing",
    flag: "/images/CarRacingPage/flag1.png",
  },
  {
    id: 11,
    firstname: "DANIEL",
    lastname: "HEMRIC",
    picture: "/images/Racers/Racer11.png",
    birthDay: "1992-12-04",
    team: "Kaulig Racing",
    flag: "/images/CarRacingPage/flag1.png",
  },
  {
    id: 12,
    firstname: "JUSTIN",
    lastname: "HALEY",
    picture: "/images/Racers/Racer12.png",
    birthDay: "1992-12-04",
    team: "Kaulig Racing",
    flag: "/images/CarRacingPage/flag1.png",
  },
  {
    id: 13,
    firstname: "MICHAEL",
    lastname: "MCDOWELL",
    picture: "/images/Racers/Racer13.png",
    birthDay: "1992-12-04",
    team: "Front Row Motorsports",
    flag: "/images/CarRacingPage/flag1.png",
  },
  {
    id: 14,
    firstname: "RICKY",
    lastname: "STENHOUSE JR",
    picture: "/images/Racers/Racer14.png",
    birthDay: "1992-12-04",
    team: "JTG Daugherty Racing",
    flag: "/images/CarRacingPage/flag1.png",
  },
  {
    id: 15,
    firstname: "HARRISON",
    lastname: "BURTON",
    picture: "/images/Racers/Racer15.png",
    birthDay: "1992-12-04",
    team: "Wood Brothers Racing",
    flag: "/images/CarRacingPage/flag1.png",
  },
  {
    id: 16,
    firstname: "COLE",
    lastname: "CUSTER",
    picture: "/images/Racers/Racer16.png",
    birthDay: "1992-12-04",
    team: "Stewart-Haas Racing",
    flag: "/images/CarRacingPage/flag1.png",
  },
  {
    id: 17,
    firstname: "TYLER",
    lastname: "REDDICK",
    picture: "/images/Racers/Racer17.png",
    birthDay: "1992-12-04",
    team: "Richard Childress Racing",
    flag: "/images/CarRacingPage/flag1.png",
  },
  {
    id: 18,
    firstname: "BUBBA",
    lastname: "WALLACE",
    picture: "/images/Racers/Racer18.png",
    birthDay: "1992-12-04",
    team: "23XI Racing",
    flag: "/images/CarRacingPage/flag1.png",
  },
];
