import Head from "next/head";
import Script from "next/script";
import "../styles/globals.scss";
import "bootstrap/dist/css/bootstrap.min.css";
import "react-datepicker/dist/react-datepicker.css";
import "rsuite/dist/rsuite.css";
import "swiper/css";
import "swiper/css/pagination";
import "swiper/css/free-mode";
import "swiper/css/navigation";
import "swiper/css/thumbs";
import { useEffect, useState } from "react";
import { Provider } from "react-redux";
import { store } from "../store";

function MyApp({ Component, pageProps }) {
  const [showChild, setShowChild] = useState(false);
  useEffect(() => {
    setShowChild(true);
    import("bootstrap/dist/js/bootstrap");
    import("bootstrap/dist/js/bootstrap.bundle");
  }, []);

  if (!showChild) {
    return null;
  }
  if (typeof window === "undefined") {
    return <></>;
  } else {
    return (
      <Provider store={store}>
        <Head>
          <meta charset="utf-8" />
          <title>LIO HOLDING</title>
          <meta name="description" content="Generated by create next app" />
          <meta
            property="zalo-platform-site-verification"
            content="NlFW6QhNR28knTmYxiS92XNKfJtvfNvbD38"
          ></meta>
          <meta name="theme-color" content="#000000"></meta>
          {/* <meta name="image" content="images/Logo/favicon.png"></meta>
          <meta name="description" content=""></meta>
          <meta name="og:image" content="assets/images/Logo/favicon.png"></meta> */}
          <meta name="og:description" content=""></meta>
          <link href="/images/Logo/Logo11.png" rel="icon" />
          <link href="/images/Logo/Logo11.png" rel="apple-touch-icon"></link>
          <link rel="preconnect" href="https://fonts.googleapis.com" />
          <link
            rel="preconnect"
            href="https://fonts.gstatic.com"
            crossOrigin="true"
          />
        </Head>
        <Component {...pageProps} />
      </Provider>
    );
  }
}

export default MyApp;
